// Code generated by `yip schema` from protocol/*.go. DO NOT EDIT.
// Schema version 1.

export type JobState = "queued" | "running" | "waiting" | "review_ready" | "completed" | "failed" | "cancelled";

export type ReviewState = "requested" | "queued" | "reviewing" | "approved" | "changes_requested" | "comments_only" | "unable_to_review" | "cancelled";

export type RunState = "created" | "offered" | "preparing" | "running" | "awaiting_input" | "stopping" | "succeeded" | "failed" | "cancelled" | "unknown";

export interface APIError {
  code: string;
  message: string;
  recoverable: boolean;
  correlationId?: string;
  missingCapability?: string;
  details?: unknown;
}

export interface AcceptJobRequest {
  revision: string;
  version: number;
  note: string;
}

export interface ActivityItem {
  at: string;
  actor: Actor;
  type: string;
  text: string;
  roomId?: string;
  refs: Ref[];
}

export interface Actor {
  kind: string;
  id: string;
}

export interface AnswerQuestionRequest {
  body: string;
  clientKey: string;
}

export interface Approval {
  id: string;
  runId: string;
  jobId: string;
  engineerId: string;
  action: ApprovalAction;
  argsDigest: string;
  scope: string;
  targetRev?: string;
  status: string;
  expiresAt: string;
  decidedBy?: Actor | null;
  decidedAt?: string | null;
  source: Destination;
  version: number;
  createdAt: string;
}

export interface ApprovalAction {
  kind: string;
  summary: string;
  command?: string;
  target?: string;
  detail?: string;
}

export interface ApprovalDecisionRequest {
  decision: string;
  version: number;
  note: string;
}

export interface Artifact {
  id: string;
  hash: string;
  name: string;
  contentType: string;
  size: number;
  kind: string;
  runId?: string;
  jobId?: string;
  roomId?: string;
  projectId?: string;
  revision?: string;
  createdAt: string;
}

export interface Bootstrap {
  user: User;
  org: Org;
  rooms: Room[];
  engineers: Engineer[];
  projects: Project[];
  nodes: Node[];
  cursor: number;
  csrfToken: string;
  preferences: Preferences;
  serverTime: string;
  version: string;
  demo: boolean;
  providers: ProviderSummary[];
}

export interface CancelJobRequest {
  reason: string;
  includeChildren: boolean;
}

export interface CatchupItem {
  kind: string;
  title: string;
  detail: string;
  at: string;
  actorId?: string;
  roomId?: string;
  threadId?: string;
  messageId?: string;
  refs: Ref[];
  eventSeq: number;
}

export interface Check {
  id: string;
  jobId: string;
  runId: string;
  nodeId: string;
  name: string;
  command: string;
  exitCode: number;
  passed: boolean;
  revision: string;
  logArtifactId?: string;
  durationMs: number;
  summary?: string;
  createdAt: string;
}

export interface ChecksSummary {
  state: string;
  passed: number;
  failed: number;
  pending: number;
  total: number;
}

export interface CleanupWorkspaceRequest {
  confirm: string;
  force: boolean;
}

export interface CreateEngineerRequest {
  name: string;
  handle: string;
  role: string;
  description: string;
  instructions: string;
  capabilityTags: string[];
  provider: ProviderPreference;
}

export interface CreateEnrollmentRequest {
  name: string;
}

export interface CreateProjectRequest {
  name: string;
  description: string;
  instructions: string;
  policy: ProjectPolicy;
  roomIds: string[];
  repos?: PutRepoRequest[];
}

export interface CreateRoomRequest {
  name: string;
  purpose: string;
  kind: string;
  private: boolean;
  replyMode: string;
  stewardId: string;
  engineerIds: string[];
  projectIds: string[];
}

export interface Decision {
  id: string;
  scope: DecisionScope;
  title: string;
  body: string;
  status: string;
  supersedesId?: string;
  supersededById?: string;
  createdBy: Actor;
  acceptedBy?: Actor | null;
  sources: Source[];
  visibleRoomIds: string[];
  version: number;
  createdAt: string;
  acceptedAt?: string | null;
}

export interface DecisionActionRequest {
  action: string;
  version: number;
}

export interface DecisionRequest {
  scope: DecisionScope;
  title: string;
  body: string;
  sources: Source[];
  supersedesId?: string;
  accept: boolean;
}

export interface DecisionScope {
  kind: string;
  id: string;
}

export interface Destination {
  roomId: string;
  threadId?: string;
  messageId?: string;
}

export interface DiagnosticBundle {
  generatedAt: string;
  hubVersion: string;
  goVersion: string;
  platform: string;
  schemaVersion: number;
  health: HealthCheck[];
  counts: Record<string, number>;
  work: Record<string, number>;
  machines: DiagnosticNode[];
  recentFailures: DiagnosticFailure[];
  excluded: string[];
}

export interface DiagnosticFailure {
  at: string;
  provider: string;
  machine: string;
  state: string;
  reason: string;
}

export interface DiagnosticNode {
  name: string;
  status: string;
  platform: string;
  runnerVersion: string;
  lastSeenAt?: string | null;
  providers: DiagnosticProvider[];
}

export interface DiagnosticProvider {
  provider: string;
  version: string;
  tested: boolean;
  authState: string;
  billing: string;
}

export interface Diagnostics {
  version: string;
  dataDir: string;
  dbSizeBytes: number;
  artifactBytes: number;
  diskFreeBytes: number;
  queueDepth: number;
  activeRuns: number;
  pendingOutbox: number;
  pendingApprovals: number;
  failedRuns24h: number;
  nodes: Node[];
  sseClients: number;
  lastBackupAt?: string | null;
  checks: HealthCheck[];
}

export interface Engineer {
  id: string;
  orgId: string;
  name: string;
  handle: string;
  role: string;
  description: string;
  instructions: string;
  capabilityTags: string[];
  provider: ProviderPreference;
  hue: number;
  avatarId?: string;
  archived: boolean;
  versionId: string;
  versionNo: number;
  version: number;
  roomIds: string[];
  activeJobIds: string[];
  createdAt: string;
  updatedAt: string;
}

export interface EngineerNote {
  id: string;
  engineerId: string;
  kind: string;
  scope: DecisionScope;
  body: string;
  status: string;
  supersedesId?: string;
  supersededById?: string;
  createdBy: Actor;
  acceptedBy?: Actor | null;
  sources: Source[];
  visibleRoomIds: string[];
  reviewAfter: string;
  version: number;
  createdAt: string;
  acceptedAt?: string | null;
}

export interface EngineerVersion {
  id: string;
  engineerId: string;
  versionNo: number;
  name: string;
  role: string;
  description: string;
  instructions: string;
  capabilityTags: string[];
  provider: ProviderPreference;
  createdAt: string;
}

export interface Enrollment {
  id: string;
  token?: string;
  name: string;
  expiresAt: string;
  hubUrl: string;
  hubFingerprint: string;
  command: string;
}

export interface Event {
  schemaVersion: number;
  eventId: string;
  orgId: string;
  sequence: number;
  type: string;
  actor: Actor;
  causeId?: string;
  rootRequestId?: string;
  roomId?: string;
  threadId?: string;
  jobId?: string;
  runId?: string;
  occurredAt: string;
  payload?: unknown;
}

export interface ExecutionProfile {
  name: string;
  available: boolean;
  reason?: string;
  summary: string;
}

export interface Finding {
  id: string;
  roundId: string;
  severity: string;
  body: string;
  file?: string;
  line?: number;
  evidence?: string;
  status: string;
  replies: FindingReply[];
  createdAt: string;
}

export interface FindingReply {
  id: string;
  findingId: string;
  author: Actor;
  body: string;
  evidence?: string;
  revision?: string;
  createdAt: string;
}

export interface Grant {
  id: string;
  projectId: string;
  engineerId: string;
  access: string;
  actions: string[];
}

export interface HealthCheck {
  name: string;
  ok: boolean;
  detail: string;
}

export interface Job {
  id: string;
  orgId: string;
  kind: string;
  title: string;
  objective: string;
  acceptance: string[];
  state: JobState;
  waitingReason?: string;
  stateDetail?: string;
  ownerId: string;
  contributors: string[];
  parentId?: string;
  followsId?: string;
  rootRequestId: string;
  source: Destination;
  projectId?: string;
  repoId?: string;
  revision?: Revision | null;
  requiresPeerReview: boolean;
  requiresHumanReview: boolean;
  completionRequested: boolean;
  summary?: string;
  depth: number;
  priority: number;
  currentRunId?: string;
  nodeId?: string;
  lastActivity?: string;
  lastActivityAt?: string | null;
  reviewerIds: string[];
  version: number;
  createdAt: string;
  updatedAt: string;
  completedAt?: string | null;
}

export interface JobDetail {
  job: Job;
  runs: Run[];
  checks: Check[];
  artifacts: Artifact[];
  reviews: Review[];
  questions: Question[];
  approvals: Approval[];
  pullRequests: PullRequest[];
  children: Job[];
  decisions: Decision[];
  activity: ActivityItem[];
  inputs: JobInput[];
  missing: string[];
  revisions: RevisionRecord[];
  followUps: Job[];
  quarantined: QuarantinedOutput[];
}

export interface JobInput {
  id: string;
  jobId: string;
  runId?: string;
  body: string;
  delivery: string;
  messageId?: string;
  createdAt: string;
  deliveredAt?: string | null;
}

export interface JobInputRequest {
  body: string;
  clientKey: string;
  questionId?: string;
}

export interface JobInputResponse {
  input: JobInput;
  message?: Message | null;
}

export interface LinkPullRequestRequest {
  repoId: string;
  number: number;
  url: string;
  jobId: string;
}

export interface Location {
}

export interface MarkReadRequest {
  seq: number;
}

export interface Member {
  kind: string;
  id: string;
}

export interface MembershipPreview {
  roomId: string;
  engineerId: string;
  visibleMessageCount: number;
  privateRoom: boolean;
  explanation: string;
}

export interface Mention {
  kind: string;
  id: string;
}

export interface MergeStatus {
  merged: boolean;
  mergeable: string;
  reasons: string[];
}

export interface Message {
  id: string;
  orgId: string;
  roomId: string;
  threadId?: string;
  seq: number;
  author: Actor;
  body: string;
  kind: string;
  mentions: Mention[];
  projectIds: string[];
  refs: Ref[];
  replyToId?: string;
  runId?: string;
  jobId?: string;
  clientKey?: string;
  reactions: ReactionSummary[];
  thread?: ThreadSummary | null;
  revision: number;
  editedAt?: string | null;
  deletedAt?: string | null;
  createdAt: string;
  attachments?: Artifact[];
}

export interface MessagePage {
  messages: Message[];
  hasMore: boolean;
}

export interface Model {
  id: string;
  label: string;
  default?: boolean;
  description?: string;
}

export interface Node {
  id: string;
  name: string;
  hostname: string;
  os: string;
  arch: string;
  fingerprint: string;
  status: string;
  draining: boolean;
  lastSeenAt?: string | null;
  capacity: NodeCapacity;
  providers: ProviderInstallation[];
  profiles: ExecutionProfile[];
  toolchains: Record<string, string>;
  activeRunIds: string[];
  runnerVersion: string;
  serviceState?: string;
  lastActivity?: string;
  createdAt: string;
  revokedAt?: string | null;
  workspaces: NodeWorkspace[];
}

export interface NodeActionRequest {
  drain: boolean;
}

export interface NodeCapacity {
  slots: number;
  used: number;
  cpus: number;
  memMb: number;
  diskFreeMb: number;
  diskPressure: boolean;
}

export interface NodeWorkspace {
  name: string;
  kind: string;
  ref: string;
  branch?: string;
  head?: string;
  changes: number;
  sizeMb: number;
  sizeBytes: number;
  sizeKnown: boolean;
  sizeApprox?: boolean;
  modifiedAt: string;
  inUse: boolean;
  jobId?: string;
  jobTitle?: string;
  jobState?: string;
  jobKind?: string;
  published: boolean;
  blocked?: string;
}

export interface NoteActionRequest {
  action: string;
  version: number;
}

export interface NoteRequest {
  scope: DecisionScope;
  body: string;
  supersedesId?: string;
}

export interface Org {
  id: string;
  name: string;
  createdAt: string;
}

export interface Overview {
  since?: string | null;
  catchup: CatchupItem[];
  work: WorkRow[];
  decisions: Decision[];
  questions: Question[];
  roomId: string;
}

export interface PostMessageRequest {
  body: string;
  threadId?: string;
  replyToId?: string;
  mentions: Mention[];
  projectIds: string[];
  clientKey: string;
  jobId?: string;
}

export interface PostMessageResponse {
  message: Message;
  duplicate: boolean;
  dispatched: string[];
  input?: JobInput | null;
  resolvedQuestionIds: string[];
}

export interface Preferences {
  theme: string;
  density: string;
  sendKey: string;
  notify: string;
  lastSeenAt: string;
  mutedRoomIds?: string[];
}

export interface PreferencesRequest {
  preferences: Preferences;
}

export interface ProfileRequest {
  name: string;
}

export interface Project {
  id: string;
  orgId: string;
  name: string;
  description: string;
  instructions: string;
  policy: ProjectPolicy;
  repos: Repo[];
  grants: Grant[];
  roomIds: string[];
  version: number;
  createdAt: string;
}

export interface ProjectPolicy {
  requirePeerReview: boolean;
  requireHumanReview: boolean;
  autoPublish: boolean;
  checks: string[];
  executionProfile: string;
  requires?: string[];
}

export interface ProviderCapabilities {
  structuredEvents: boolean;
  toolApprovals: boolean;
  userQuestions: boolean;
  sessionResume: boolean;
  activeSteering: boolean;
  usageTelemetry: boolean;
  sandbox: boolean;
  modelEnumeration: boolean;
  readOnly: boolean;
  mcpTools: boolean;
}

export interface ProviderInstallation {
  provider: string;
  version: string;
  path: string;
  authState: string;
  authDetail?: string;
  account?: string;
  billing: string;
  profileId: string;
  capabilities: ProviderCapabilities;
  models: Model[];
  testedVersion?: string;
  tested: boolean;
  limitations?: string[];
  updatedAt: string;
}

export interface ProviderPreference {
  provider: string;
  model?: string;
  profileId?: string;
  alternatives?: string[];
  allowApiBilling?: boolean;
}

export interface ProviderProfile {
  id: string;
  provider: string;
  label: string;
  billing: string;
  maxConcurrency: number;
  pausedUntil?: string | null;
}

export interface ProviderProfileRequest {
  maxConcurrency: number;
}

export interface ProviderSummary {
  provider: string;
  label: string;
  readyNodes: string[];
  billing: string;
  fake: boolean;
}

export interface PullRequest {
  id: string;
  repoId: string;
  jobId?: string;
  forge: string;
  host: string;
  owner: string;
  name: string;
  number: number;
  url: string;
  title: string;
  state: string;
  base: string;
  head: string;
  remoteAuthor: string;
  viewerActor: string;
  checks: ChecksSummary;
  merge: MergeStatus;
  remoteReviews: RemoteReview[];
  lastSyncedAt?: string | null;
}

export interface PutGrantRequest {
  access: string;
  actions: string[];
}

export interface PutRepoRequest {
  name: string;
  remoteUrl: string;
  defaultBranch: string;
  forge: string;
  forgeRepo: string;
}

export interface QuarantinedOutput {
  id: string;
  runId: string;
  nodeId: string;
  epoch: number;
  currentEpoch: number;
  kind: string;
  summary: string;
  receivedAt: string;
}

export interface Question {
  id: string;
  jobId: string;
  askerId: string;
  recipient: Actor;
  missingFact: string;
  contextChecked: string;
  dependentStep: string;
  continuingWith: string;
  status: string;
  source: Destination;
  messageId: string;
  answerMessageId?: string;
  createdAt: string;
  answeredAt?: string | null;
}

export interface ReactRequest {
  emoji: string;
  remove: boolean;
}

export interface ReactionSummary {
  emoji: string;
  count: number;
  mine: boolean;
}

export interface Ref {
  kind: string;
  id: string;
}

export interface RemoteReview {
  actor: string;
  state: string;
  commitId: string;
  submittedAt: string;
  externalId: string;
  publishedByEngineerId?: string;
}

export interface Repo {
  id: string;
  projectId: string;
  name: string;
  remoteUrl: string;
  defaultBranch: string;
  forge: string;
  forgeRepo?: string;
  createdAt: string;
  sourceBundleId?: string;
  importedAt?: string | null;
}

export interface RetryJobRequest {
  fromCheckpoint: boolean;
  nodeId?: string;
  reason: string;
}

export interface Review {
  id: string;
  jobId: string;
  authorId: string;
  reviewerId: string;
  source: Destination;
  targetKind: string;
  criteria: string;
  state: ReviewState;
  currentRound: number;
  pullRequestId?: string;
  rounds: ReviewRound[];
  createdAt: string;
  updatedAt: string;
}

export interface ReviewRound {
  id: string;
  reviewId: string;
  number: number;
  target: ReviewTarget;
  state: ReviewState;
  summary?: string;
  reviewerRunId?: string;
  reviewJobId?: string;
  supersededBy?: string;
  findings: Finding[];
  createdAt: string;
  decidedAt?: string | null;
}

export interface ReviewTarget {
  kind: string;
  repoId?: string;
  base?: string;
  head?: string;
  artifactId?: string;
  hash?: string;
  pullRequestId?: string;
}

export interface Revision {
  repoId: string;
  branch?: string;
  base: string;
  head?: string;
}

export interface RevisionRecord {
  repoId: string;
  branch: string;
  base: string;
  head: string;
  diffArtifactId: string;
  diffHash: string;
  filesChanged: number;
  insertions: number;
  deletions: number;
  summary: string;
}

export interface Room {
  id: string;
  orgId: string;
  name: string;
  kind: string;
  purpose: string;
  private: boolean;
  replyMode: string;
  stewardId?: string;
  members: Member[];
  projectIds: string[];
  archived: boolean;
  lastSeq: number;
  version: number;
  createdAt: string;
  lastReadSeq: number;
  unreadCount: number;
  mentionCount: number;
}

export interface Run {
  id: string;
  jobId: string;
  attempt: number;
  engineerId: string;
  engineerVersionId: string;
  nodeId?: string;
  provider: string;
  model?: string;
  profileId?: string;
  mode: string;
  state: RunState;
  leaseEpoch: number;
  leaseExpiresAt?: string | null;
  heartbeatAt?: string | null;
  vendorSessionId?: string;
  destination: Destination;
  causeId: string;
  rootRequestId: string;
  previousRunId?: string;
  branch?: string;
  baseRev?: string;
  resultRev?: string;
  terminalReason?: string;
  lastActivity?: string;
  lastActivityAt?: string | null;
  usage?: Usage | null;
  createdAt: string;
  startedAt?: string | null;
  endedAt?: string | null;
}

export interface RunActivity {
  runId: string;
  seq: number;
  kind: string;
  text: string;
  tool?: string;
  data?: unknown;
  at: string;
}

export interface SearchResult {
  kind: string;
  id: string;
  title: string;
  snippet: string;
  roomId?: string;
  threadId?: string;
  jobId?: string;
  at?: string | null;
}

export interface SetupRequest {
  bootstrapSecret: string;
  orgName: string;
  name: string;
  handle: string;
  password: string;
}

export interface SetupStatus {
  needsSetup: boolean;
  orgName?: string;
  version: string;
}

export interface SignInRequest {
  handle: string;
  password: string;
}

export interface Source {
  kind: string;
  id: string;
  roomId?: string;
}

export interface ThreadSummary {
  replyCount: number;
  lastReplyAt: string;
  participants: Actor[];
}

export interface UpdateEngineerRequest {
  version: number;
  name?: string | null;
  role?: string | null;
  description?: string | null;
  instructions?: string | null;
  capabilityTags?: string[] | null;
  provider?: ProviderPreference | null;
  archived?: boolean | null;
}

export interface UpdateProjectRequest {
  version: number;
  name?: string | null;
  description?: string | null;
  instructions?: string | null;
  policy?: ProjectPolicy | null;
}

export interface UpdateRoomRequest {
  version: number;
  name?: string | null;
  purpose?: string | null;
  private?: boolean | null;
  replyMode?: string | null;
  stewardId?: string | null;
  projectIds?: string[] | null;
  archived?: boolean | null;
}

export interface Usage {
  source: string;
  inputTokens?: number | null;
  outputTokens?: number | null;
  costUsd?: number | null;
  billing: string;
}

export interface User {
  id: string;
  orgId: string;
  name: string;
  handle: string;
  avatarId?: string;
  createdAt: string;
}

export interface WorkRow {
  job: Job;
  projectName?: string;
  roomName?: string;
  nodeName?: string;
  lastConfirmed: string;
  lastConfirmedAt?: string | null;
  blocker?: string;
  questions?: Question[];
  runState?: RunState;
}

export interface WorkspaceInfo {
  name: string;
  kind: string;
  ref: string;
  branch?: string;
  head?: string;
  changes: number;
  sizeMb: number;
  sizeBytes: number;
  sizeKnown: boolean;
  sizeApprox?: boolean;
  modifiedAt: string;
  inUse: boolean;
}

export interface zone {
}

export interface zoneTrans {
}

