package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/binbandit/yip/internal/schemagen"
	"github.com/binbandit/yip/protocol"
)

// apiRoots are the browser-facing resources and request bodies.
var apiRoots = []any{
	protocol.Bootstrap{}, protocol.SetupStatus{}, protocol.SetupRequest{}, protocol.SignInRequest{}, protocol.APIError{},
	protocol.Room{}, protocol.CreateRoomRequest{}, protocol.UpdateRoomRequest{}, protocol.MembershipPreview{},
	protocol.Message{}, protocol.MessagePage{}, protocol.PostMessageRequest{}, protocol.PostMessageResponse{}, protocol.ReactRequest{},
	protocol.MarkReadRequest{}, protocol.Engineer{}, protocol.EngineerVersion{}, protocol.CreateEngineerRequest{}, protocol.UpdateEngineerRequest{},
	protocol.Project{}, protocol.CreateProjectRequest{}, protocol.UpdateProjectRequest{}, protocol.PutRepoRequest{}, protocol.PutGrantRequest{},
	protocol.Job{}, protocol.JobDetail{}, protocol.JobInputRequest{}, protocol.JobInputResponse{}, protocol.CancelJobRequest{},
	protocol.RetryJobRequest{}, protocol.AcceptJobRequest{}, protocol.Review{}, protocol.PullRequest{}, protocol.LinkPullRequestRequest{},
	protocol.Approval{}, protocol.ApprovalDecisionRequest{}, protocol.Question{}, protocol.AnswerQuestionRequest{},
	protocol.Node{}, protocol.Enrollment{}, protocol.CreateEnrollmentRequest{}, protocol.NodeActionRequest{},
	protocol.Decision{}, protocol.DecisionRequest{}, protocol.DecisionActionRequest{}, protocol.Overview{}, protocol.SearchResult{},
	protocol.RunActivity{}, protocol.Diagnostics{}, protocol.Event{}, protocol.PreferencesRequest{}, protocol.RevisionRecord{},
}

// runnerRoots are the runner protocol frames and payloads.
var runnerRoots = []any{
	protocol.Frame{}, protocol.Hello{}, protocol.Welcome{}, protocol.RunnerCapabilities{}, protocol.Heartbeat{}, protocol.LeaseRenewal{},
	protocol.OfferRun{}, protocol.RunAck{}, protocol.CommandAck{}, protocol.RunEvent{}, protocol.RunTerminal{}, protocol.ToolCall{},
	protocol.ToolResult{}, protocol.ApprovalRequest{}, protocol.ResolveApproval{}, protocol.DeliverInput{}, protocol.InputDelivered{},
	protocol.CancelRun{}, protocol.Ack{}, protocol.Reconcile{}, protocol.CheckRecord{}, protocol.RevisionRecord{}, protocol.PairRequest{},
	protocol.PairResponse{},
}

var enums = map[string][]string{
	"JobState":    {"queued", "running", "waiting", "review_ready", "completed", "failed", "cancelled"},
	"RunState":    {"created", "offered", "preparing", "running", "awaiting_input", "stopping", "succeeded", "failed", "cancelled", "unknown"},
	"ReviewState": {"requested", "queued", "reviewing", "approved", "changes_requested", "comments_only", "unable_to_review", "cancelled"},
}

func runSchema(args []string) error {
	fs := flag.NewFlagSet("schema", flag.ExitOnError)
	out := fs.String("out", "protocol/schema", "directory for JSON schemas")
	ts := fs.String("ts", "web/src/lib/api/types.gen.ts", "TypeScript output file")
	_ = fs.Parse(args)
	if err := os.MkdirAll(*out, 0o755); err != nil {
		return err
	}
	api := schemagen.New(apiRoots...)
	b, err := api.JSONSchema(fmt.Sprintf("https://getyip.dev/schema/v%d/api.json", protocol.SchemaVersion), "yip browser API v1", enums)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(*out, "api.v1.json"), append(b, '\n'), 0o644); err != nil {
		return err
	}
	runner := schemagen.New(runnerRoots...)
	b, err = runner.JSONSchema(fmt.Sprintf("https://getyip.dev/schema/v%d/runner.json", protocol.RunnerProtocolVersion), "yip runner protocol v1", enums)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(*out, "runner.v1.json"), append(b, '\n'), 0o644); err != nil {
		return err
	}
	if *ts != "" {
		if err := os.MkdirAll(filepath.Dir(*ts), 0o755); err != nil {
			return err
		}
		header := fmt.Sprintf("// Code generated by `yip schema` from protocol/*.go. DO NOT EDIT.\n// Schema version %d.\n\n", protocol.SchemaVersion)
		if err := os.WriteFile(*ts, []byte(api.TypeScript(header, enums)), 0o644); err != nil {
			return err
		}
	}
	fmt.Println("wrote", filepath.Join(*out, "api.v1.json"), filepath.Join(*out, "runner.v1.json"), *ts)
	return nil
}
